### ISSUE TITLE
Cannot import name 'smart_unicode'

### ISSUE THREAD

**Issue by mrgrifon** [alexhayes/django-premailer#3]
Hello Alex Hayes!

I am  sorry for bothering your. I found that it's impossible to use this library with python3 
Please read this article https://github.com/edoburu/django-polymorphic-tree/issues/30

"In Django 1.7 (and I believe 1.6) smart_unicode is replaced with smart_text under Python 3."

Kind regards,
- Oleg

**Comment by alexhayes** [comment]
This is fixed in v0.2.0 which is now on pypi - https://pypi.python.org/pypi/django-premailer
