### ISSUE TITLE
I wish the pull request was accepted and a new version was uploaded to PyPi

### ISSUE THREAD

**Issue by gabn88** [alexhayes/django-premailer#5]
:)

**Comment by madisvain** [comment]
I wish the same thing!

**Comment by alexhayes** [comment]
Apologies folks, I wasn't aware there was a PR or issues, perhaps these emails hit my spam filter or they were missed??? Not sure, will test the spam filter idea upon raise of next issue.

So, yes, I do plan on supporting this and will merge the PR shortly once I've got tox setup testing 2.7, 3.3-3.5.
